name: Lab08

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:

  BUILD_TYPE: Release

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build Docker image
      run: docker build -t logger .
    
    - name: Run container
      run: |
        mkdir -p ./logs
        docker run \
          -v "$(pwd)/logs:/lab08/logs" \
          -e LOG_PATH=/lab08/logs/log.txt \
          logger
     
    # - name: Upload DEB artifact
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: ubuntu-latest-deb-pack
    #     path: build/*.deb
    
  # create_release:
  #     needs: job
  #     runs-on: ubuntu-latest
  #     permissions:
  #       contents: write 

  #     steps:
  #     - uses: actions/checkout@v4

  #     - name: download_ubuntu_deb
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: ubuntu-latest-deb-pack
  #         path: artifacts/linux
          
      # - name: Create Release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     tag_name: v1.${{ github.run_number }}
      #     name: Release v1.${{ github.run_number }}
      #     files: |
      #       artifacts/linux/*.deb 
      #       logs/log.txt
      
