name: Lab08

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:

  BUILD_TYPE: Release

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build Docker image
      run: sudo docker build -t logger .
    
    - name: Run container
      run: sudo docker run --name HWCON logger 
        
    - name: doker cp
      run: sudo docker cp HWCON:app/build/hello_world_application/hello_world .
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: dep_artifact
        path: ${{ github.workspace }}/hello_world
          
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
         tag_name: v1.${{ github.run_number }}
         name: Release v1.${{ github.run_number }}
         files: |
           hello_world
      
